# Generated by Django 2.2.18 on 2022-02-05 14:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('orgin', models.CharField(max_length=50)),
                ('descreption', models.TextField(default='Lorem Ipsum Dolor Sit Amet, Consectetur Adipisicing Elit. Omnis, Maxime.')),
                ('images', models.ImageField(blank=True, null=True, upload_to='photos/%y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Categorys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('orgin', models.CharField(max_length=50)),
                ('images', models.ImageField(blank=True, null=True, upload_to='photos/%y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('descreption', models.TextField(default='none')),
                ('Expir_date', models.DateField(default=datetime.datetime.now)),
                ('Price', models.IntegerField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='photos/%y/%m/%d')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Brands')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Categorys')),
            ],
        ),
    ]
