# Generated by Django 2.2.18 on 2022-02-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorys',
            name='descreption',
            field=models.TextField(default='Lorem Ipsum Dolor Sit Amet, Consectetur Adipisicing Elit. Omnis, Maxime.'),
        ),
        migrations.AlterField(
            model_name='products',
            name='descreption',
            field=models.TextField(default='Lorem Ipsum Dolor Sit Amet, Consectetur Adipisicing Elit. Omnis, Maxime.'),
        ),
    ]
